[package]
authors       = ["Havunen <sampo.kivisto@live.fi>"]
description   = "SWC plugin for InfernoJS."
documentation = "https://github.com/infernojs/swc-plugin-inferno"
edition       = "2021"
include       = ["Cargo.toml", "src/**/*.rs"]
license       = "MIT"
name          = "swc-plugin-inferno"
repository    = "https://github.com/infernojs/swc-plugin-inferno.git"
version       = "0.0.22"

[lib]
crate-type = ["cdylib", "rlib"]
bench = false

[features]
concurrent = ["rayon"]
default    = ["serde-impl"]
serde-impl = ["serde"]

[profile.release]
# This removes more dead code
codegen-units = 1
lto = true
# Optimize for size
opt-level = "s"

# Strip debug symbols
strip = "symbols"

[dependencies]
base64    = "0.22.1"
dashmap   = "6.0.1"
indexmap  = "2.5.0"
once_cell = "1.19.0"
rayon     = { version = "1.10.0", optional = true }
serde     = { version = "1.0.209", features = ["derive"], optional = true }
sha-1     = "=0.10.1"

swc_core = { version = "0.102.2", features = [
    "swc_atoms",
    "swc_common",
    "swc_ecma_ast",
    "swc_ecma_utils",
    "ecma_plugin_transform",
    "ecma_utils",
    "ecma_visit",
    "ecma_ast",
    "common",
] }
swc_ecma_parser            = { version = "0.149.1" }
swc_config                 = { version = "0.1.15" }

[dev-dependencies]
swc_ecma_codegen            = { version = "0.155.1" }
swc_ecma_transforms_compat  = { version = "0.171.0" }
swc_ecma_transforms_module  = { version = "0.190.0" }
swc_ecma_transforms_testing = { version = "0.148.0" }
swc_ecma_transforms         = { version = "0.239.0" }
testing                     = { version = "0.39.0" }
