use crate::inferno_flags::VNodeFlags;

/// The vNode flags of an element with this tag name, from the `lib/vNodeTypes.js` table of
/// babel-plugin-inferno
pub fn parse_vnode_flag(tag: &str) -> u16 {
    (match tag {
        "input" => VNodeFlags::InputElement,
        "textarea" => VNodeFlags::TextareaElement,
        "select" => VNodeFlags::SelectElement,
        "altGlyph"
        | "altGlyphDef"
        | "altGlyphItem"
        | "animate"
        | "animateColor"
        | "animateMotion"
        | "animateTransform"
        | "circle"
        | "clipPath"
        | "color-profile"
        | "cursor"
        | "defs"
        | "desc"
        | "discard"
        | "ellipse"
        | "feBlend"
        | "feColorMatrix"
        | "feComponentTransfer"
        | "feComposite"
        | "feConvolveMatrix"
        | "feDiffuseLighting"
        | "feDisplacementMap"
        | "feDistantLight"
        | "feDropShadow"
        | "feFlood"
        | "feFuncA"
        | "feFuncB"
        | "feFuncG"
        | "feFuncR"
        | "feGaussianBlur"
        | "feImage"
        | "feMerge"
        | "feMergeNode"
        | "feMorphology"
        | "feOffset"
        | "fePointLight"
        | "feSpecularLighting"
        | "feSpotLight"
        | "feTile"
        | "feTurbulence"
        | "filter"
        | "font-face"
        | "font-face-format"
        | "font-face-name"
        | "font-face-src"
        | "font-face-uri"
        | "foreignObject"
        | "g"
        | "glyph"
        | "glyphRef"
        | "hkern"
        | "line"
        | "linearGradient"
        | "marker"
        | "mask"
        | "metadata"
        | "missing-glyph"
        | "mpath"
        | "path"
        | "pattern"
        | "polygon"
        | "polyline"
        | "radialGradient"
        | "rect"
        | "set"
        | "stop"
        | "svg"
        | "switch"
        | "symbol"
        | "text"
        | "textPath"
        | "tref"
        | "tspan"
        | "unknown"
        | "use"
        | "view"
        | "vkern"
        | "hatch"
        | "hatchpath"
        | "mesh"
        | "meshgradient"
        | "meshpatch"
        | "meshrow"
        | "solidcolor" => VNodeFlags::SvgElement,
        _ => VNodeFlags::HtmlElement,
    }) as u16
}
